version: '3.8'

services:
  web:
    build: .
    command: uv run uvicorn web.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    env_file:
      - .env

  celery:
    build: .
    command: uv run celery -A worker.main worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: uv run celery -A worker.main beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  flower:
    build: .
    command: uv run celery -A worker.main flower --loglevel=info
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
