# # Exported from Render on 2024-12-04T14:30:06Z
# services:
# - type: web
#   name: nba-pickem
#   runtime: docker
#   repo: https://github.com/dgliwa/nba-pickem
#   plan: free
#   region: virginia
#   dockerContext: .
#   dockerfilePath: ./Dockerfile
#   dockerCommand: "uv run uvicorn web.main:app --host 0.0.0.0"
#   envVars:
#       - key: CELERY_BROKER_URL
#         fromService:
#           name: pickem-redis
#           type: redis
#           property: connectionString
# - type: worker
#   name: nba-pickem-worker
#   runtime: docker
#   repo: https://github.com/dgliwa/nba-pickem
#   plan: standard
#   region: virginia
#   dockerContext: .
#   dockerfilePath: ./Dockerfile
#   dockerCommand: "uv run celery -A worker.main worker --loglevel=info"
#   envVars:
#       - key: CELERY_BROKER_URL
#         fromService:
#           name: pickem-redis
#           type: redis
#           property: connectionString
# - type: web
#   name: celery-admin-ui
#   runtime: docker
#   repo: https://github.com/dgliwa/nba-pickem
#   plan: free
#   region: virginia
#   dockerContext: .
#   dockerfilePath: ./Dockerfile
#   dockerCommand: "uv run celery -A worker.main flower --loglevel=info"
#   envVars:
#       - key: CELERY_BROKER_URL
#         fromService:
#           name: pickem-redis
#           type: redis
#           property: connectionString
# - type: redis
#   name: pickem-redis
#   region: virginia
#   plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
#   maxmemoryPolicy: noeviction # recommended policy for queues
#   ipAllowList: [] # only allow internal connections
# version: "1"
