# Exported from Render on 2024-12-04T14:30:06Z
services:
- type: web
  name: nba-pickem
  runtime: docker
  repo: https://github.com/dgliwa/nba-pickem
  plan: free
  region: virginia
  dockerContext: .
  dockerfilePath: ./Dockerfile
- type: redis
  name: celery-redis
  region: virginia
  plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
  maxmemoryPolicy: noeviction # recommended policy for queues
  ipAllowList: [] # only allow internal connections
version: "1"
